package gogen

const (
	defaultGeneratedTest     = "// Code generated by github.com/randallmlough/gogen, DO NOT EDIT.\n\n"
	defaultTemplateExtension = ".gotpl"
)

var (
	DefaultConfig = Config{
		GeneratedHeader:         false,
		generatedText:           defaultGeneratedTest,
		Description:             "",
		FileNotice:              false,
		FileNoticeText:          "// this was a generated file",
		RegionTags:              false,
		SkipChildren:            true,
		TemplateExtensionSuffix: defaultTemplateExtension,
	}
)

type Config struct {
	GeneratedHeader bool
	generatedText   string
	// Description is documentation written after the generated header and before any template data
	Description string
	FileNotice  bool
	// FileNotice is notice written below the package line
	FileNoticeText string
	RegionTags     bool

	SkipChildren            bool
	TemplateExtensionSuffix string
}

func (c *Config) apply(cfg *Config) error {
	c.generatedText = defaultGeneratedTest
	*cfg = *c
	return nil
}

func (c *Config) check() error {
	if c.TemplateExtensionSuffix == "" {
		c.TemplateExtensionSuffix = defaultTemplateExtension
	}
	return nil
}
