package gogen

var (
	DefaultConfig = Config{
		GeneratedHeader: false,
		Description:     "",
		generatedText:   "// Code generated by github.com/randallmlough/gogen, DO NOT EDIT.\n\n",
		FileNotice:      false,
		FileNoticeText:  "// this was a generated file",
		RegionTags:      false,
		SkipChildren:    true,
	}
)

type Config struct {
	GeneratedHeader bool
	generatedText   string
	// Description is documentation written after the generated header and before any template data
	Description string
	FileNotice  bool
	// FileNotice is notice written below the package line
	FileNoticeText string
	RegionTags     bool

	SkipChildren bool
}

func (c *Config) apply(cfg *Config) {
	c.generatedText = cfg.generatedText
	*cfg = *c
}
