// Code generated by github.com/randallmlough/gogen, DO NOT EDIT.

// file generation is awesome
package output

import (
	"fmt"
)

func talk() {
	name := "john"
	fmt.Println("Hello there", name)
	greeting("Hello to you too.")
}

func greeting(say string) {
	fmt.Println(say)
}
